name: travel_go
description: a travel application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  flutter_native_splash: ^2.3.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_svg: ^2.0.7
  socket_io_client: ^2.0.3+1
  provider: ^6.0.5
  dio: ^5.3.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#213555"
  min_sdk_android: 21

flutter_native_splash:
  color: "#213555"
  image: "assets/images/splash_screen.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/screenshot/



